In [1]:
x=input("enter ")
l=len(x)
i=0
while (i < l+1):
    print(x[i-1],end='')
    i=i-1

enter 09980
08990

IndexError: string index out of range

In [10]:
import pandas as pd

In [11]:
import numpy as np

In [3]:
l1=['a','b','c','d','e','f']
l1[:]

['a', 'b', 'c', 'd', 'e', 'f']

In [4]:
l1[3:4]

['d']

In [5]:
l1[::-1]

['f', 'e', 'd', 'c', 'b', 'a']

In [8]:
l1[2:-2:2]

['c']

In [9]:
l1[::3]

['a', 'd']

In [15]:
l1.append('g')

In [16]:
l1.append('h')

In [17]:
l1[::3]

['a', 'd', 'g']

In [18]:
l1[:]


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'g', 'h']

In [19]:
l1.remove('g')

In [20]:
l1[:]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [21]:
type(l1)

list

In [22]:
max(l1)

'h'

In [23]:
min(l1)

'a'

In [24]:
l1[-1:-3]

[]

In [25]:
l1[3:-4]

['d']

In [26]:
l1[-5:-1]

['d', 'e', 'f', 'g']

In [29]:
l1[1:6:-3]

[]

In [3]:
t1=('an','ap','ak','afk','cd')

In [ ]:
i=0
while(True):
    if i+1<5:
        i=i+1
        continue
print(i+1,end="")
if i==30:
    break
i=i+1

In [2]:
n =int(input("Enter Number: "))
if n>=1 and n<=100:
    if  n%2== 0:
        print("Not Weird")
    else:
        print("Weird")

Enter Number: 6
Not Weird


In [3]:
#np.array()
#np.reshape(*,*,'C')
#np.reshape(*,*,'F')

In [1]:
import numpy as np
mydata=np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
np.reshape(mydata,(5,4)) #default is opposite in R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
matr1=np.reshape(mydata,(5,4),order='C') #used to print any specific number
matr1[2,2]

10

In [10]:
matr1=np.reshape(mydata,(5,4),order='F') 
matr1

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
l1=['i','w','f']
l2=['u','i','s']
l3=[1,2,3]
[l1,l2,l3]

[['i', 'w', 'f'], ['u', 'i', 's'], [1, 2, 3]]

In [12]:
l1=['i','w','f','r']
l2=['u','i','s']
l3=[1,2,3]
[l1,l2,l3]

[['i', 'w', 'f', 'r'], ['u', 'i', 's'], [1, 2, 3]]

In [15]:
np.array([l1,l2,l3])

array([['i', 'w', 'f'],
       ['u', 'i', 's'],
       ['1', '2', '3']], dtype='<U1')

In [16]:
print(np.array([l1,l2,l3]))

[['i' 'w' 'f']
 ['u' 'i' 's']
 ['1' '2' '3']]


In [24]:
#What is happening here when I run this we've just created an object which is called a dictionary and it's kind of like a list.
#But the difference is that a list is an ordered set of elements whereas a dictionary is not ordered.
#It's got the key
#dictionaries

In [19]:
dict1={'k1':'v1','k2':'v2','k3':'v3'}

In [23]:
dict1['k1']

'v1'

In [38]:
import numpy as np
year=np.array(['2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2014-15'])
gp=np.array([79,78,75,81,76,79,62,76,77,69])
fg=np.array([.480,.476,.484,.489,.489,.503,.510,.531,.565,.567,.486])
mgp=np.array([42.5,40.9,40.4,37.7,39.0,38.8,37.5,37.9,37.7,36.1])
ppg=np.array([31.4,27.3,30.0,28.4,29.7,26.7,27.1,26.8,27.1,25.3])
d1={'Year':year,'GP':gp,'MGP':mgp,'FG':fg,'PPG':ppg}
print(d1)

{'Year': array(['2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11',
       '2011-12', '2012-13', '2014-15'], dtype='<U7'), 'GP': array([79, 78, 75, 81, 76, 79, 62, 76, 77, 69]), 'MGP': array([42.5, 40.9, 40.4, 37.7, 39. , 38.8, 37.5, 37.9, 37.7, 36.1]), 'FG': array([0.48 , 0.476, 0.484, 0.489, 0.489, 0.503, 0.51 , 0.531, 0.565,
       0.567, 0.486]), 'PPG': array([31.4, 27.3, 30. , 28.4, 29.7, 26.7, 27.1, 26.8, 27.1, 25.3])}


In [29]:
#matrix operator
path=os.listdr("checxnet/")

NameError: name 'os' is not defined

In [33]:
import openpyxl
wb=openpyxl.load_workbook("we(<filename>).xlsx")
print(wb.sheetnames)
ws=wb['Sheet1']
print(ws)

OSError: [Errno 22] Invalid argument: 'we(<filename>).xlsx'

In [34]:
wb.create_sheet("newsheet")
wb.save('we.xlsx')

NameError: name 'wb' is not defined

In [39]:
import pandas as pd
data=pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [40]:
data['b']

0.5

In [42]:
population_dict={'California':3833521,'Texas':26448193,'New York':1965}
population=pd.Series(population_dict)
population

California     3833521
Texas         26448193
New York          1965
dtype: int64

In [43]:
'a' in data

True

In [44]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [45]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [46]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64